# Generated by Django 2.0.5 on 2019-07-26 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time_created', models.BigIntegerField(default=1564144879)),
                ('time_modified', models.BigIntegerField(default=1564144879)),
                ('permissions', models.ManyToManyField(to='permission.PermissionModel')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
