# Generated by Django 2.0.5 on 2019-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('actors', models.ManyToManyField(to='actor.ActorModel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
