version: "2"

services:
  # mysql
  mysql:
    image: mysql:5.7.21
    volumes_from:
      - mysql-data
    ports:
      - "8806:3306"
    container_name: "mysql-app-django"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: root
      MYSQL_PASSWORD: pwd

  # mysql data
  mysql-data:
    image: mysql:5.7.21
    container_name: "mysql-data-app-django"
    volumes:
      - ./db/mysql:/var/lib/mysql
    command: "true"

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-app-django"
    ports:
      - 8084:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
